### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [reinforced/Reinforced.Lattice.Samples#1]
Hey! is possible to get source code of Reinforced.Lattice ?

**Comment by pavel-b-novikov** [comment]
No, it is not possible since Reinforced.Lattice is proprietary. You can find legacy packages on nuget, but it is not going to be available in open source anymore.

**Comment by pavel-b-novikov** [comment]
Anyway, thank you for your interest. Reinforced.Lattice will be launched (I hope) in the summer of 2022 as commercial product. You will get promo coupon for free subscription.
